Added proposal
210104-msbi-reston/training-code pull request #5
Opened 2021-02-08 06:14 UTC by Dmilut

Added proposal from group 5

2021-02-08 17:05 UTC, nikhilshahdemoaccount reviewed
This looks to be really a great project domain, 

looking forward to see it in action, 

however if you can provide more details on what are the dimensions, how will you be collecting the data, from which all sources, what kind of data can be visualized



Kindly elaborate More on this

2021-02-09 15:20 UTC, kaurrevature requested changes

2021-02-09 15:20 UTC, kaurrevature commented on P2-Proposals/synopsis.md
> +...
Please add the architecture

2021-02-10 05:51 UTC, Dmilut commented on P2-Proposals/synopsis.md
> +...
Fixed

2021-02-10 05:51 UTC, Dmilut commented
Updated

2021-02-10 15:19 UTC, Dmilut commented
I updated the proposal, please check it

2021-02-10 19:35 UTC, kaurrevature commented
Good work @Dmilut , it is looking great!!

2021-02-10 19:36 UTC, merged